
#  默认值
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:1234/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true

---

spring:
  profiles: dev
  datasource:
     url: jdbc:mysql://127.0.0.1:1235/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
---

spring:
  profiles: test
  datasource:
     url: jdbc:mysql://127.0.0.1:1236/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true

---

# online环境数据库的相关配置
spring:
  profiles: online
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
